name: scp files
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up SSH key and agent
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p 22 ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: Rsync files
        run: |
          rsync -azv --delete --exclude-from='.gitignore' \
            --chmod=Fug=rwX,Fo=,Dug=rwxs \
            --chown=${{ secrets.USERNAME }}:shared \
            ./ ${{ secrets.USERNAME }}@${{ secrets.HOST }}:${{ secrets.DEPLOY_PATH }}

